# Generated by Django 5.0.6 on 2025-03-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_registration_picture_alter_registration_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='picture',
        ),
    ]
