# Generated by Django 5.0.6 on 2025-03-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_registration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='usertype',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Patiant', 'Patiant'), ('Donar', 'Donar')], default='Patiant', max_length=100, null=True),
        ),
    ]
