# Generated by Django 5.0.6 on 2025-03-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_registration_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
