# Generated by Django 5.0.6 on 2025-03-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_registration_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
