# Generated by Django 5.0.6 on 2025-03-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_donateblood_distics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateblood',
            name='bloodType',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=400),
        ),
    ]
