# Generated by Django 5.0.6 on 2025-03-20 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_bloodrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='typeOfBlood',
        ),
    ]
