# Generated by Django 5.0.6 on 2025-03-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_remove_bloodrequest_typeofblood'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('Accepted', 'Accepted')], null=True),
        ),
    ]
