# Generated by Django 5.0.6 on 2025-03-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_bloodrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('Accepted', 'Accepted')], default='pending', null=True),
        ),
    ]
