# Generated by Django 5.0.6 on 2025-03-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_alter_bloodrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='danateTime',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='massage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
