# Generated by Django 5.0.6 on 2025-03-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_remove_bloodrequest_danatetime_bloodrequest_massage'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateblood',
            name='totalRequest',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
