# Generated by Django 5.0.6 on 2025-03-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_donateblood_totalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateblood',
            name='done',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
