# Generated by Django 5.0.6 on 2025-03-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0010_donateblood_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateblood',
            name='done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
