# Generated by Django 5.0.6 on 2025-04-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0011_alter_donateblood_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateblood',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
